implement decrypt command

diff --git a/gramps b/gramps
--- a/gramps
+++ b/gramps
@@ -36,6 +36,7 @@ gramps_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Generate a key pair and display the private key\n" "init   "
   printf "  %s   Encrypt and save a file using the public key\n" "encrypt"
+  printf "  %s   Decrypt a file using the offline private key\n" "decrypt"
   echo
 
   # :command.long_usage
@@ -128,6 +129,48 @@ gramps_encrypt_usage() {
     # :argument.usage
     printf "  %s\n" "INPUT_PATH"
     printf "    Path to a file you want to encrypt\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+gramps_decrypt_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "gramps decrypt - Decrypt a file using the offline private key\n"
+    echo
+
+  else
+    printf "gramps decrypt - Decrypt a file using the offline private key\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  gramps decrypt INPUT_PATH [OUTPUT_PATH]\n"
+  printf "  gramps decrypt --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "INPUT_PATH"
+    printf "    Path to a file you want to decrypt\n"
+    echo
+
+    # :argument.usage
+    printf "  %s\n" "OUTPUT_PATH"
+    printf "    Path where you want to save the decrypted file (or stdout if not specified)\n"
     echo
 
   fi
@@ -270,6 +313,54 @@ gramps_encrypt_command() {
 
 }
 
+# :command.function
+gramps_decrypt_command() {
+  # src/decrypt_command.sh
+  # shellcheck shell=bash
+
+  # shellcheck disable=SC2154  # variables like ${args} are defined in main script
+  input_path="${args[input_path]}"
+  test -f "${input_path}" || panic "File not found: ${input_path}"
+
+  output_path="${args[output_path]:-}"
+
+  private_key_input="$(cat | tr --delete '[:space:]')"
+  input_len="${#private_key_input}"
+
+  test "${input_len}" -eq 60 || panic "Invalid key format"
+
+  version="${private_key_input:0:2}"
+
+  test "${version}" = "01" || panic "Key generated by different version of gramps"
+
+  age_identity="AGE-SECRET-KEY-1${private_key_input:2:58}"
+
+  age_cmd=(
+      age --decrypt
+      --identity -
+  )
+
+  if [ "${output_path}" != "" ]; then
+      test ! -e "${output_path}" || panic "Already exists: ${output_path}"
+      age_cmd+=(--output "${output_path}")
+  fi
+
+  age_cmd+=("${input_path}")
+
+  process_stderr() {
+      # process `age --decrypt` stderr to improve known error messages.
+      age_stderr="$(cat)"
+      if echo "${age_stderr}" | grep --fixed-strings "age: error: no identity matched any of the recipients" &> /dev/null; then
+          panic "Unable to decrypt; perhaps a mistyped key?"
+      else
+          echo "${age_stderr}" >&2
+      fi
+  }
+
+  echo "${age_identity}" | "${age_cmd[@]}" 2> >(process_stderr)
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -310,6 +401,13 @@ parse_requirements() {
       action="encrypt"
       shift
       gramps_encrypt_parse_requirements "$@"
+      shift $#
+      ;;
+
+    decrypt)
+      action="decrypt"
+      shift
+      gramps_decrypt_parse_requirements "$@"
       shift $#
       ;;
 
@@ -475,6 +573,66 @@ gramps_encrypt_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+gramps_decrypt_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        gramps_decrypt_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="decrypt"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['input_path']+x} ]]; then
+
+          args['input_path']=$1
+          shift
+        elif [[ -z ${args['output_path']+x} ]]; then
+
+          args['output_path']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['input_path']+x} ]]; then
+    printf "missing required argument: INPUT_PATH\nusage: gramps decrypt INPUT_PATH [OUTPUT_PATH]\n" >&2
+    exit 1
+  fi
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -495,6 +653,7 @@ run() {
   case "$action" in
     "init") gramps_init_command ;;
     "encrypt") gramps_encrypt_command ;;
+    "decrypt") gramps_decrypt_command ;;
   esac
 }
 
